### ISSUE TITLE
Pass log payload into custom error handler

### ISSUE THREAD

**Issue by obokaiwele** [komamitsu/fluency#70]
The data that could not be logged is available in the same context where the CustomErrorHandler is called.
It would be great to pass the payload into to the error handler.

My use case is to try to emit via Fluency, if that fails, then log the same data to system journald.
So when Fluency reports an error, I need to also grab the payload so I can try again with Journald.

Thanks.

**Comment by obokaiwele** [comment]
This would be similar to other Fluentd logger implementations. Python example:
```python
import msgpack
from io import BytesIO

def overflow_handler(pendings):
    unpacker = msgpack.Unpacker(BytesIO(pendings))
    for unpacked in unpacker:
        print(unpacked)

logger = sender.FluentSender('app', host='host', port=24224, buffer_overflow_handler=overflow_handler)
```


The unlogged data is passed to the Custom Error Handler

**Comment by komamitsu** [comment]
Fluency sends in-memory buffered data asynchronously. If it fails to send data, the unsent data will be retried to be sent later automatically. So it's no use reporting unsent data via an error handler since the unsent data can be already sent by a retry after reporting that and it causes duplicated events.

**Comment by komamitsu** [comment]
Closing this issue. If you still have any trouble on this issue, feel free reopen it.
